version: '3.8'
services:
  db:
    image: bitnami/postgresql:16.3.0
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=report_creator_ai
    volumes:
      - report_creator_ai_data:/bitnami/postgresql

volumes:
  report_creator_ai_data: