"""add file_id to reports table

Revision ID: 3d206326f7ab
Revises: 991e41fcb7ac
Create Date: 2024-07-28 01:29:44.669912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d206326f7ab'
down_revision: Union[str, None] = '991e41fcb7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('file_id', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'file_id')
    # ### end Alembic commands ###
